# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  # admin-monitor - Spring Boot
  - package-ecosystem: "maven"
    directory: "/admin-monitor"
    schedule:
      interval: "weekly"
      day: "saturday"

  # openapi-server - Spring Boot
  - package-ecosystem: "maven"
    directory: "/openapi-server"
    schedule:
      interval: "weekly"
      day: "saturday"

  # tanstack-start-client-app - pnpm
  - package-ecosystem: "npm"
    directory: "/tanstack-start-client-app"
    schedule:
      interval: "weekly"
      day: "saturday"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
