spring:
  profiles:
    active: ${SPRING_PROFILE:dev}

  application:
    name: admin-monitor

  boot:
    admin:
      instance-auth:
        # Uses credentials from instance metadata
        enabled: true

server:
  port: ${PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

admin-monitor:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
