spring:
  profiles:
    active: ${SPRING_PROFILE:dev}

  application:
    name: openapi-server

  threads:
    virtual:
      enabled: true

  datasource:
    url: ${DB_JDBC_URL}

  jpa:
    hibernate:
      ddl-auto: none  # Hibernate will not manage schema; Liquibase handles it

    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  # Liquibase integration
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-root.yaml

  # Spring Boot Admin integration
  boot:
    admin:
      client:
        url: ${ADMIN_MONITOR_URL}  # URL of your Admin Server
        username: ${ADMIN_MONITOR_USERNAME}
        password: ${ADMIN_MONITOR_PASSWORD}

        instance:
          service-base-url: ${SERVICE_BASE_URL:${RENDER_EXTERNAL_URL}}
          management-base-url: ${MANAGEMENT_BASE_URL:${RENDER_EXTERNAL_URL}}
          metadata:
            user.name: ${ACTUATOR_USERNAME}
            user.password: ${ACTUATOR_PASSWORD}

server:
  port: ${PORT}

  servlet:
    session:
      cookie:
        domain: ${SESSION_COOKIE_DOMAIN:}
        same-site: ${SESSION_COOKIE_SAME_SITE:lax}
        secure: ${SESSION_COOKIE_SECURE:false}
        http-only: ${SESSION_COOKIE_HTTP_ONLY:true}

logging:
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:info}

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all actuator endpoints

  endpoint:
    health:
      show-details: when_authorized
      roles: [ "ACTUATOR" ]

    env:
      show-values: when_authorized
      roles: [ "ACTUATOR" ]

    configprops:
      show-values: when_authorized
      roles: [ "ACTUATOR" ]

  info:
    env:
      enabled: true  # Enable the info endpoint with environment details

# MARK: Custom application properties

electric:
  url: ${ELECTRIC_URL}
  secret: ${ELECTRIC_SECRET}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
