/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  CurrentUserResponse,
  SigninRequestBody,
  SignupRequestBody,
} from './openAPIDefinition.schemas'

import { axiosApi } from '../api/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const postSignup = (
  signupRequestBody: SignupRequestBody,
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<void>(
    {
      url: `/api/auth/signup`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: signupRequestBody,
      signal,
    },
    options,
  )
}

export const getPostSignupMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postSignup>>,
    TError,
    { data: SignupRequestBody },
    TContext
  >
  request?: SecondParameter<typeof axiosApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postSignup>>,
  TError,
  { data: SignupRequestBody },
  TContext
> => {
  const mutationKey = ['postSignup']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postSignup>>,
    { data: SignupRequestBody }
  > = (props) => {
    const { data } = props ?? {}

    return postSignup(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostSignupMutationResult = NonNullable<
  Awaited<ReturnType<typeof postSignup>>
>
export type PostSignupMutationBody = SignupRequestBody
export type PostSignupMutationError = unknown

export const usePostSignup = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postSignup>>,
      TError,
      { data: SignupRequestBody },
      TContext
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postSignup>>,
  TError,
  { data: SignupRequestBody },
  TContext
> => {
  return useMutation(getPostSignupMutationOptions(options), queryClient)
}
export const postSignout = (
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<void>(
    { url: `/api/auth/signout`, method: 'POST', signal },
    options,
  )
}

export const getPostSignoutMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postSignout>>,
    TError,
    void,
    TContext
  >
  request?: SecondParameter<typeof axiosApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postSignout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['postSignout']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postSignout>>,
    void
  > = () => {
    return postSignout(requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostSignoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof postSignout>>
>

export type PostSignoutMutationError = unknown

export const usePostSignout = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postSignout>>,
      TError,
      void,
      TContext
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postSignout>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getPostSignoutMutationOptions(options), queryClient)
}
export const postSignin = (
  signinRequestBody: SigninRequestBody,
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<void>(
    {
      url: `/api/auth/signin`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: signinRequestBody,
      signal,
    },
    options,
  )
}

export const getPostSigninMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postSignin>>,
    TError,
    { data: SigninRequestBody },
    TContext
  >
  request?: SecondParameter<typeof axiosApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postSignin>>,
  TError,
  { data: SigninRequestBody },
  TContext
> => {
  const mutationKey = ['postSignin']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postSignin>>,
    { data: SigninRequestBody }
  > = (props) => {
    const { data } = props ?? {}

    return postSignin(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostSigninMutationResult = NonNullable<
  Awaited<ReturnType<typeof postSignin>>
>
export type PostSigninMutationBody = SigninRequestBody
export type PostSigninMutationError = unknown

export const usePostSignin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postSignin>>,
      TError,
      { data: SigninRequestBody },
      TContext
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postSignin>>,
  TError,
  { data: SigninRequestBody },
  TContext
> => {
  return useMutation(getPostSigninMutationOptions(options), queryClient)
}
export const getCurrentUser = (
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<CurrentUserResponse>(
    { url: `/api/auth/current-user`, method: 'GET', signal },
    options,
  )
}

export const getGetCurrentUserQueryKey = () => {
  return [`/api/auth/current-user`] as const
}

export const getGetCurrentUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
  >
  request?: SecondParameter<typeof axiosApi>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetCurrentUserQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({
    signal,
  }) => getCurrentUser(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCurrentUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUser>>
>
export type GetCurrentUserQueryError = unknown

export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetCurrentUserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}
