/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  CsrfTokenResponse,
  SimpleResponse,
} from './openAPIDefinition.schemas'

import { axiosApi } from '../api/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getInitCsrf = (
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<SimpleResponse>(
    { url: `/api/public/init-csrf`, method: 'GET', signal },
    options,
  )
}

export const getGetInitCsrfQueryKey = () => {
  return [`/api/public/init-csrf`] as const
}

export const getGetInitCsrfQueryOptions = <
  TData = Awaited<ReturnType<typeof getInitCsrf>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getInitCsrf>>, TError, TData>
  >
  request?: SecondParameter<typeof axiosApi>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetInitCsrfQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getInitCsrf>>> = ({
    signal,
  }) => getInitCsrf(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getInitCsrf>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInitCsrfQueryResult = NonNullable<
  Awaited<ReturnType<typeof getInitCsrf>>
>
export type GetInitCsrfQueryError = unknown

export function useGetInitCsrf<
  TData = Awaited<ReturnType<typeof getInitCsrf>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getInitCsrf>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInitCsrf>>,
          TError,
          Awaited<ReturnType<typeof getInitCsrf>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetInitCsrf<
  TData = Awaited<ReturnType<typeof getInitCsrf>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getInitCsrf>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInitCsrf>>,
          TError,
          Awaited<ReturnType<typeof getInitCsrf>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetInitCsrf<
  TData = Awaited<ReturnType<typeof getInitCsrf>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getInitCsrf>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetInitCsrf<
  TData = Awaited<ReturnType<typeof getInitCsrf>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getInitCsrf>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetInitCsrfQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const getCsrfToken = (
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<CsrfTokenResponse>(
    { url: `/api/public/csrf-token`, method: 'GET', signal },
    options,
  )
}

export const getGetCsrfTokenQueryKey = () => {
  return [`/api/public/csrf-token`] as const
}

export const getGetCsrfTokenQueryOptions = <
  TData = Awaited<ReturnType<typeof getCsrfToken>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getCsrfToken>>, TError, TData>
  >
  request?: SecondParameter<typeof axiosApi>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetCsrfTokenQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCsrfToken>>> = ({
    signal,
  }) => getCsrfToken(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCsrfToken>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCsrfTokenQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCsrfToken>>
>
export type GetCsrfTokenQueryError = unknown

export function useGetCsrfToken<
  TData = Awaited<ReturnType<typeof getCsrfToken>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCsrfToken>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCsrfToken>>,
          TError,
          Awaited<ReturnType<typeof getCsrfToken>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetCsrfToken<
  TData = Awaited<ReturnType<typeof getCsrfToken>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCsrfToken>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCsrfToken>>,
          TError,
          Awaited<ReturnType<typeof getCsrfToken>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetCsrfToken<
  TData = Awaited<ReturnType<typeof getCsrfToken>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCsrfToken>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetCsrfToken<
  TData = Awaited<ReturnType<typeof getCsrfToken>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCsrfToken>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetCsrfTokenQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}
