/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  PostMailHelloHtmlParams,
  PostMailHelloParams,
  PostUpperCaseParams,
  SimpleResponse,
} from './openAPIDefinition.schemas'

import { axiosApi } from '../api/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const postUpperCase = (
  params: PostUpperCaseParams,
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<SimpleResponse>(
    { url: `/api/upper-case`, method: 'POST', params, signal },
    options,
  )
}

export const getPostUpperCaseMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postUpperCase>>,
    TError,
    { params: PostUpperCaseParams },
    TContext
  >
  request?: SecondParameter<typeof axiosApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postUpperCase>>,
  TError,
  { params: PostUpperCaseParams },
  TContext
> => {
  const mutationKey = ['postUpperCase']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postUpperCase>>,
    { params: PostUpperCaseParams }
  > = (props) => {
    const { params } = props ?? {}

    return postUpperCase(params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostUpperCaseMutationResult = NonNullable<
  Awaited<ReturnType<typeof postUpperCase>>
>

export type PostUpperCaseMutationError = unknown

export const usePostUpperCase = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postUpperCase>>,
      TError,
      { params: PostUpperCaseParams },
      TContext
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postUpperCase>>,
  TError,
  { params: PostUpperCaseParams },
  TContext
> => {
  return useMutation(getPostUpperCaseMutationOptions(options), queryClient)
}
export const postMailHello = (
  params: PostMailHelloParams,
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<SimpleResponse>(
    { url: `/api/mail/hello`, method: 'POST', params, signal },
    options,
  )
}

export const getPostMailHelloMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postMailHello>>,
    TError,
    { params: PostMailHelloParams },
    TContext
  >
  request?: SecondParameter<typeof axiosApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postMailHello>>,
  TError,
  { params: PostMailHelloParams },
  TContext
> => {
  const mutationKey = ['postMailHello']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postMailHello>>,
    { params: PostMailHelloParams }
  > = (props) => {
    const { params } = props ?? {}

    return postMailHello(params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostMailHelloMutationResult = NonNullable<
  Awaited<ReturnType<typeof postMailHello>>
>

export type PostMailHelloMutationError = unknown

export const usePostMailHello = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postMailHello>>,
      TError,
      { params: PostMailHelloParams },
      TContext
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postMailHello>>,
  TError,
  { params: PostMailHelloParams },
  TContext
> => {
  return useMutation(getPostMailHelloMutationOptions(options), queryClient)
}
export const postMailHelloHtml = (
  params: PostMailHelloHtmlParams,
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<SimpleResponse>(
    { url: `/api/mail/hello-html`, method: 'POST', params, signal },
    options,
  )
}

export const getPostMailHelloHtmlMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postMailHelloHtml>>,
    TError,
    { params: PostMailHelloHtmlParams },
    TContext
  >
  request?: SecondParameter<typeof axiosApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postMailHelloHtml>>,
  TError,
  { params: PostMailHelloHtmlParams },
  TContext
> => {
  const mutationKey = ['postMailHelloHtml']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postMailHelloHtml>>,
    { params: PostMailHelloHtmlParams }
  > = (props) => {
    const { params } = props ?? {}

    return postMailHelloHtml(params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostMailHelloHtmlMutationResult = NonNullable<
  Awaited<ReturnType<typeof postMailHelloHtml>>
>

export type PostMailHelloHtmlMutationError = unknown

export const usePostMailHelloHtml = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postMailHelloHtml>>,
      TError,
      { params: PostMailHelloHtmlParams },
      TContext
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postMailHelloHtml>>,
  TError,
  { params: PostMailHelloHtmlParams },
  TContext
> => {
  return useMutation(getPostMailHelloHtmlMutationOptions(options), queryClient)
}
export const getHello = (
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<SimpleResponse>(
    { url: `/api/public/hello`, method: 'GET', signal },
    options,
  )
}

export const getGetHelloQueryKey = () => {
  return [`/api/public/hello`] as const
}

export const getGetHelloQueryOptions = <
  TData = Awaited<ReturnType<typeof getHello>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getHello>>, TError, TData>
  >
  request?: SecondParameter<typeof axiosApi>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetHelloQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getHello>>> = ({
    signal,
  }) => getHello(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getHello>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHelloQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHello>>
>
export type GetHelloQueryError = unknown

export function useGetHello<
  TData = Awaited<ReturnType<typeof getHello>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHello>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHello>>,
          TError,
          Awaited<ReturnType<typeof getHello>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetHello<
  TData = Awaited<ReturnType<typeof getHello>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHello>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHello>>,
          TError,
          Awaited<ReturnType<typeof getHello>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetHello<
  TData = Awaited<ReturnType<typeof getHello>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHello>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetHello<
  TData = Awaited<ReturnType<typeof getHello>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHello>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetHelloQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}
