/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  PostTranslateParams,
  SimpleResponse,
} from './openAPIDefinition.schemas'

import { axiosApi } from '../api/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const postTranslate = (
  params: PostTranslateParams,
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<SimpleResponse>(
    {
      url: `http://localhost:8080/api/translate`,
      method: 'POST',
      params,
      signal,
    },
    options,
  )
}

export const getPostTranslateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTranslate>>,
    TError,
    { params: PostTranslateParams },
    TContext
  >
  request?: SecondParameter<typeof axiosApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTranslate>>,
  TError,
  { params: PostTranslateParams },
  TContext
> => {
  const mutationKey = ['postTranslate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTranslate>>,
    { params: PostTranslateParams }
  > = (props) => {
    const { params } = props ?? {}

    return postTranslate(params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostTranslateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTranslate>>
>

export type PostTranslateMutationError = unknown

export const usePostTranslate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postTranslate>>,
      TError,
      { params: PostTranslateParams },
      TContext
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postTranslate>>,
  TError,
  { params: PostTranslateParams },
  TContext
> => {
  return useMutation(getPostTranslateMutationOptions(options), queryClient)
}
export const getInitCsrf = (
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<SimpleResponse>(
    {
      url: `http://localhost:8080/api/public/init-csrf`,
      method: 'GET',
      signal,
    },
    options,
  )
}

export const getGetInitCsrfQueryKey = () => {
  return [`http://localhost:8080/api/public/init-csrf`] as const
}

export const getGetInitCsrfQueryOptions = <
  TData = Awaited<ReturnType<typeof getInitCsrf>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getInitCsrf>>, TError, TData>
  >
  request?: SecondParameter<typeof axiosApi>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetInitCsrfQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getInitCsrf>>> = ({
    signal,
  }) => getInitCsrf(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getInitCsrf>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInitCsrfQueryResult = NonNullable<
  Awaited<ReturnType<typeof getInitCsrf>>
>
export type GetInitCsrfQueryError = unknown

export function useGetInitCsrf<
  TData = Awaited<ReturnType<typeof getInitCsrf>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getInitCsrf>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInitCsrf>>,
          TError,
          Awaited<ReturnType<typeof getInitCsrf>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetInitCsrf<
  TData = Awaited<ReturnType<typeof getInitCsrf>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getInitCsrf>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInitCsrf>>,
          TError,
          Awaited<ReturnType<typeof getInitCsrf>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetInitCsrf<
  TData = Awaited<ReturnType<typeof getInitCsrf>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getInitCsrf>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetInitCsrf<
  TData = Awaited<ReturnType<typeof getInitCsrf>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getInitCsrf>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetInitCsrfQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const getHello = (
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<SimpleResponse>(
    { url: `http://localhost:8080/api/public/hello`, method: 'GET', signal },
    options,
  )
}

export const getGetHelloQueryKey = () => {
  return [`http://localhost:8080/api/public/hello`] as const
}

export const getGetHelloQueryOptions = <
  TData = Awaited<ReturnType<typeof getHello>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getHello>>, TError, TData>
  >
  request?: SecondParameter<typeof axiosApi>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetHelloQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getHello>>> = ({
    signal,
  }) => getHello(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getHello>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHelloQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHello>>
>
export type GetHelloQueryError = unknown

export function useGetHello<
  TData = Awaited<ReturnType<typeof getHello>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHello>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHello>>,
          TError,
          Awaited<ReturnType<typeof getHello>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetHello<
  TData = Awaited<ReturnType<typeof getHello>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHello>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHello>>,
          TError,
          Awaited<ReturnType<typeof getHello>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetHello<
  TData = Awaited<ReturnType<typeof getHello>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHello>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetHello<
  TData = Awaited<ReturnType<typeof getHello>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHello>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetHelloQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}
