/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export interface SimpleResponse {
  message: string
}

export interface SignupRequestBody {
  /** @minLength 1 */
  email: string
  /** @minLength 1 */
  password: string
}

export interface GrantedAuthority {
  authority?: string
}

export interface CurrentUserResponse {
  id?: number
  email?: string
  authorities?: GrantedAuthority[]
}

export type PostTranslateParams = {
  text: string
}

export type PostSigninParams = {
  email: string
  password: string
}
