/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export interface TodoUpdateRequestBody {
  id: string
  /** @minLength 1 */
  description: string
  completed: boolean
}

export interface TodoResponse {
  id: string
  description: string
  completed: boolean
  ownerId: string
  createdAt: string
  updatedAt: string
}

export interface SimpleResponse {
  message: string
}

export interface TodoAddRequestBody {
  /** @minLength 1 */
  description: string
}

export interface SignupRequestBody {
  /** @minLength 1 */
  email: string
  /** @minLength 1 */
  password: string
}

export interface SigninRequestBody {
  /** @minLength 1 */
  email: string
  /** @minLength 1 */
  password: string
}

export interface GrantedAuthority {
  authority?: string
}

export interface CurrentUserResponse {
  id?: number
  email?: string
  authorities?: GrantedAuthority[]
}

export interface TodoDeleteRequestBody {
  id: string
}

export type PostUpperCaseParams = {
  text: string
}

export type GetElectricTodoList200Item = { [key: string]: unknown }
