/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export interface TodoResponse {
  id: number
  description: string
  completed: boolean
  ownerId: number
  createdAt: string
  updatedAt: string
}

export interface SimpleResponse {
  message: string
}

export interface SignupRequestBody {
  /** @minLength 1 */
  email: string
  /** @minLength 1 */
  password: string
}

export interface GrantedAuthority {
  authority?: string
}

export interface CurrentUserResponse {
  id?: number
  email?: string
  authorities?: GrantedAuthority[]
}

export type PutTodoUpdateParams = {
  id: number
  description: string
  completed: boolean
}

export type PostUpperCaseParams = {
  text: string
}

export type PostTodoAddParams = {
  description: string
}

export type PostSigninParams = {
  email: string
  password: string
}

export type DeleteTodoRemoveParams = {
  id: number
}
