/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type { SimpleResponse } from './openAPIDefinition.schemas.ts'

import { axiosApi } from '../api/axios.ts'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

export const getHeartbeat = (
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<SimpleResponse>(
    { url: `/api/public/heartbeat`, method: 'GET', signal },
    options,
  )
}

export const getGetHeartbeatQueryKey = () => {
  return [`/api/public/heartbeat`] as const
}

export const getGetHeartbeatQueryOptions = <
  TData = Awaited<ReturnType<typeof getHeartbeat>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getHeartbeat>>, TError, TData>
  >
  request?: SecondParameter<typeof axiosApi>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetHeartbeatQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getHeartbeat>>> = ({
    signal,
  }) => getHeartbeat(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getHeartbeat>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHeartbeatQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHeartbeat>>
>
export type GetHeartbeatQueryError = unknown

export function useGetHeartbeat<
  TData = Awaited<ReturnType<typeof getHeartbeat>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHeartbeat>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHeartbeat>>,
          TError,
          Awaited<ReturnType<typeof getHeartbeat>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetHeartbeat<
  TData = Awaited<ReturnType<typeof getHeartbeat>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHeartbeat>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHeartbeat>>,
          TError,
          Awaited<ReturnType<typeof getHeartbeat>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetHeartbeat<
  TData = Awaited<ReturnType<typeof getHeartbeat>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHeartbeat>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetHeartbeat<
  TData = Awaited<ReturnType<typeof getHeartbeat>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHeartbeat>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetHeartbeatQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return withQueryKey(query, queryOptions.queryKey)
}
