/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  DeleteTodoRemoveParams,
  PostTodoAddParams,
  PutTodoUpdateParams,
  TodoResponse,
} from './openAPIDefinition.schemas'

import { axiosApi } from '../api/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const putTodoUpdate = (
  params: PutTodoUpdateParams,
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<TodoResponse>(
    {
      url: `http://localhost:8080/api/todo/update`,
      method: 'PUT',
      params,
      signal,
    },
    options,
  )
}

export const getPutTodoUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putTodoUpdate>>,
    TError,
    { params: PutTodoUpdateParams },
    TContext
  >
  request?: SecondParameter<typeof axiosApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof putTodoUpdate>>,
  TError,
  { params: PutTodoUpdateParams },
  TContext
> => {
  const mutationKey = ['putTodoUpdate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putTodoUpdate>>,
    { params: PutTodoUpdateParams }
  > = (props) => {
    const { params } = props ?? {}

    return putTodoUpdate(params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PutTodoUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof putTodoUpdate>>
>

export type PutTodoUpdateMutationError = unknown

export const usePutTodoUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putTodoUpdate>>,
      TError,
      { params: PutTodoUpdateParams },
      TContext
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putTodoUpdate>>,
  TError,
  { params: PutTodoUpdateParams },
  TContext
> => {
  return useMutation(getPutTodoUpdateMutationOptions(options), queryClient)
}
export const postTodoAdd = (
  params: PostTodoAddParams,
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<TodoResponse>(
    {
      url: `http://localhost:8080/api/todo/add`,
      method: 'POST',
      params,
      signal,
    },
    options,
  )
}

export const getPostTodoAddMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTodoAdd>>,
    TError,
    { params: PostTodoAddParams },
    TContext
  >
  request?: SecondParameter<typeof axiosApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTodoAdd>>,
  TError,
  { params: PostTodoAddParams },
  TContext
> => {
  const mutationKey = ['postTodoAdd']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTodoAdd>>,
    { params: PostTodoAddParams }
  > = (props) => {
    const { params } = props ?? {}

    return postTodoAdd(params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostTodoAddMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTodoAdd>>
>

export type PostTodoAddMutationError = unknown

export const usePostTodoAdd = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postTodoAdd>>,
      TError,
      { params: PostTodoAddParams },
      TContext
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postTodoAdd>>,
  TError,
  { params: PostTodoAddParams },
  TContext
> => {
  return useMutation(getPostTodoAddMutationOptions(options), queryClient)
}
export const getTodoList = (
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<TodoResponse[]>(
    { url: `http://localhost:8080/api/todo/list`, method: 'GET', signal },
    options,
  )
}

export const getGetTodoListQueryKey = () => {
  return [`http://localhost:8080/api/todo/list`] as const
}

export const getGetTodoListQueryOptions = <
  TData = Awaited<ReturnType<typeof getTodoList>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getTodoList>>, TError, TData>
  >
  request?: SecondParameter<typeof axiosApi>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetTodoListQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodoList>>> = ({
    signal,
  }) => getTodoList(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTodoList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTodoListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTodoList>>
>
export type GetTodoListQueryError = unknown

export function useGetTodoList<
  TData = Awaited<ReturnType<typeof getTodoList>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTodoList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodoList>>,
          TError,
          Awaited<ReturnType<typeof getTodoList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetTodoList<
  TData = Awaited<ReturnType<typeof getTodoList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTodoList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodoList>>,
          TError,
          Awaited<ReturnType<typeof getTodoList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetTodoList<
  TData = Awaited<ReturnType<typeof getTodoList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTodoList>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetTodoList<
  TData = Awaited<ReturnType<typeof getTodoList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTodoList>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetTodoListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const deleteTodoRemove = (
  params: DeleteTodoRemoveParams,
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<void>(
    {
      url: `http://localhost:8080/api/todo/remove`,
      method: 'DELETE',
      params,
      signal,
    },
    options,
  )
}

export const getDeleteTodoRemoveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTodoRemove>>,
    TError,
    { params: DeleteTodoRemoveParams },
    TContext
  >
  request?: SecondParameter<typeof axiosApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteTodoRemove>>,
  TError,
  { params: DeleteTodoRemoveParams },
  TContext
> => {
  const mutationKey = ['deleteTodoRemove']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteTodoRemove>>,
    { params: DeleteTodoRemoveParams }
  > = (props) => {
    const { params } = props ?? {}

    return deleteTodoRemove(params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteTodoRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteTodoRemove>>
>

export type DeleteTodoRemoveMutationError = unknown

export const useDeleteTodoRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteTodoRemove>>,
      TError,
      { params: DeleteTodoRemoveParams },
      TContext
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteTodoRemove>>,
  TError,
  { params: DeleteTodoRemoveParams },
  TContext
> => {
  return useMutation(getDeleteTodoRemoveMutationOptions(options), queryClient)
}
