/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type { GetElectricTodoList200Item } from './openAPIDefinition.schemas'

import { axiosApi } from '../api/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getElectricTodoList = (
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<GetElectricTodoList200Item[]>(
    {
      url: `http://localhost:8080/api/electric/todo/list`,
      method: 'GET',
      signal,
    },
    options,
  )
}

export const getGetElectricTodoListQueryKey = () => {
  return [`http://localhost:8080/api/electric/todo/list`] as const
}

export const getGetElectricTodoListQueryOptions = <
  TData = Awaited<ReturnType<typeof getElectricTodoList>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getElectricTodoList>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof axiosApi>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetElectricTodoListQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getElectricTodoList>>
  > = ({ signal }) => getElectricTodoList(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getElectricTodoList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetElectricTodoListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getElectricTodoList>>
>
export type GetElectricTodoListQueryError = unknown

export function useGetElectricTodoList<
  TData = Awaited<ReturnType<typeof getElectricTodoList>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getElectricTodoList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getElectricTodoList>>,
          TError,
          Awaited<ReturnType<typeof getElectricTodoList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetElectricTodoList<
  TData = Awaited<ReturnType<typeof getElectricTodoList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getElectricTodoList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getElectricTodoList>>,
          TError,
          Awaited<ReturnType<typeof getElectricTodoList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetElectricTodoList<
  TData = Awaited<ReturnType<typeof getElectricTodoList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getElectricTodoList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetElectricTodoList<
  TData = Awaited<ReturnType<typeof getElectricTodoList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getElectricTodoList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetElectricTodoListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}
