/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  HandleElectricTodoList1200Item,
  HandleElectricTodoList1Body,
  HandleElectricTodoList200Item,
  HandleElectricTodoListBody,
} from './openAPIDefinition.schemas'

import { axiosApi } from '../api/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const handleElectricTodoList = (
  handleElectricTodoListBody: HandleElectricTodoListBody,
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<HandleElectricTodoList200Item[]>(
    {
      url: `http://localhost:8080/api/electric/todo/list`,
      method: 'GET',
      headers: { 'Content-Type': 'application/json' },
      signal,
    },
    options,
  )
}

export const getHandleElectricTodoListQueryKey = (
  handleElectricTodoListBody?: HandleElectricTodoListBody,
) => {
  return [
    `http://localhost:8080/api/electric/todo/list`,
    handleElectricTodoListBody,
  ] as const
}

export const getHandleElectricTodoListQueryOptions = <
  TData = Awaited<ReturnType<typeof handleElectricTodoList>>,
  TError = unknown,
>(
  handleElectricTodoListBody: HandleElectricTodoListBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof handleElectricTodoList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosApi>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getHandleElectricTodoListQueryKey(handleElectricTodoListBody)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof handleElectricTodoList>>
  > = ({ signal }) =>
    handleElectricTodoList(handleElectricTodoListBody, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof handleElectricTodoList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HandleElectricTodoListQueryResult = NonNullable<
  Awaited<ReturnType<typeof handleElectricTodoList>>
>
export type HandleElectricTodoListQueryError = unknown

export function useHandleElectricTodoList<
  TData = Awaited<ReturnType<typeof handleElectricTodoList>>,
  TError = unknown,
>(
  handleElectricTodoListBody: HandleElectricTodoListBody,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof handleElectricTodoList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleElectricTodoList>>,
          TError,
          Awaited<ReturnType<typeof handleElectricTodoList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useHandleElectricTodoList<
  TData = Awaited<ReturnType<typeof handleElectricTodoList>>,
  TError = unknown,
>(
  handleElectricTodoListBody: HandleElectricTodoListBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof handleElectricTodoList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleElectricTodoList>>,
          TError,
          Awaited<ReturnType<typeof handleElectricTodoList>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useHandleElectricTodoList<
  TData = Awaited<ReturnType<typeof handleElectricTodoList>>,
  TError = unknown,
>(
  handleElectricTodoListBody: HandleElectricTodoListBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof handleElectricTodoList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useHandleElectricTodoList<
  TData = Awaited<ReturnType<typeof handleElectricTodoList>>,
  TError = unknown,
>(
  handleElectricTodoListBody: HandleElectricTodoListBody,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof handleElectricTodoList>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getHandleElectricTodoListQueryOptions(
    handleElectricTodoListBody,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const handleElectricTodoList1 = (
  handleElectricTodoList1Body: HandleElectricTodoList1Body,
  options?: SecondParameter<typeof axiosApi>,
  signal?: AbortSignal,
) => {
  return axiosApi<HandleElectricTodoList1200Item[]>(
    {
      url: `http://localhost:8080/api/electric/todo/list`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: handleElectricTodoList1Body,
      signal,
    },
    options,
  )
}

export const getHandleElectricTodoList1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof handleElectricTodoList1>>,
    TError,
    { data: HandleElectricTodoList1Body },
    TContext
  >
  request?: SecondParameter<typeof axiosApi>
}): UseMutationOptions<
  Awaited<ReturnType<typeof handleElectricTodoList1>>,
  TError,
  { data: HandleElectricTodoList1Body },
  TContext
> => {
  const mutationKey = ['handleElectricTodoList1']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof handleElectricTodoList1>>,
    { data: HandleElectricTodoList1Body }
  > = (props) => {
    const { data } = props ?? {}

    return handleElectricTodoList1(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type HandleElectricTodoList1MutationResult = NonNullable<
  Awaited<ReturnType<typeof handleElectricTodoList1>>
>
export type HandleElectricTodoList1MutationBody = HandleElectricTodoList1Body
export type HandleElectricTodoList1MutationError = unknown

export const useHandleElectricTodoList1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof handleElectricTodoList1>>,
      TError,
      { data: HandleElectricTodoList1Body },
      TContext
    >
    request?: SecondParameter<typeof axiosApi>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof handleElectricTodoList1>>,
  TError,
  { data: HandleElectricTodoList1Body },
  TContext
> => {
  return useMutation(
    getHandleElectricTodoList1MutationOptions(options),
    queryClient,
  )
}
